version: '3'

services:
  frontend:
    container_name: dastone
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dastonenet
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn run dev"
    tty: true

networks:
  dastonenet:
    driver: bridge
