version: '3'

services:
  frontend:
    container_name: condo-admin
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - condomanagernet
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn run dev"
    tty: true

networks:
  condomanagernet:
    driver: bridge
